server:
    port: 9091

spring:
    application:
        name: book-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost