server:
    port: 8081

spring:
    application:
        name: zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
    routes:
        user-service:
            path: /user/**
            service-id: user-service
            strip-prefix: true
        book-service:
            path: /book/**
            service-id: book-service
            strip-prefix: true